apiVersion: v1
kind: Service
metadata:
  name: strands-coi-svc
  namespace: er
  labels:
    app: strands-coi
spec:
  selector:
    app: strands-coi
  ports:
  - name: http
    port: 8001
    targetPort: 8001
  type: ClusterIP
