apiVersion: v1
kind: Pod
metadata:
  name: busybox-efs-test
  namespace: er
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: efs-storage
      mountPath: /NAS/er
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: er-efs-pvc