apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: er-onprem-aimodels-pvc
  namespace: er
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: er-onprem-aimodels-pv