apiVersion: v1
kind: PersistentVolume
metadata:
  name: er-onprem-aimodels-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Gi
  mountOptions:
    - vers=3
  nfs:
    path: /nas_dev_aimodels
    server: 172.23.252.11
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem