apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ai-editor-recommender
  namespace: er
  labels:
    app: at-ai-editor-recommender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-ai-editor-recommender
  template:
    metadata:
      labels:
        app: at-ai-editor-recommender
    spec:
      serviceAccountName: er-bedrock-sa
      containers:
      - name: at-ai-editor-recommender
        image: ghcr.io/acspubsedsg/at-ai-editor-recommender:v0.3.3
        ports:
        - containerPort: 8012
        resources:
          limits:
            cpu: "500m"
            memory: "1024Mi"
          requests:
            cpu: "100m"
            memory: "1024Mi"
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://phoenix-svc.phoenix.svc.cluster.local:6006/v1/traces
        - name: EE_URL
          value: http://ee-api-poc-svc.er.svc.cluster.local:8010/editor_assignment_protocol/manuscript
        - name: ASSIGN_URL
          value: http://ee-api-poc-svc.er.svc.cluster.local:8010/mock/assignManuscript
      imagePullSecrets:
      - name: er-ghcr-secret